### ISSUE TITLE
Course image height

### ISSUE THREAD

**Issue by disha1202** [openedx/frontend-app-learner-dashboard#265]
The course image takes up the actual height of the image.

<img width="1440" alt="image" src="https://github.com/openedx/frontend-app-learner-dashboard/assets/58461801/493982ea-6150-45c0-bd5f-4f622bdda1e3">

Ideally the height of the course image should be fixed.

**Comment by jciasenza** [comment]
I can take this issue @arbrandes

**Comment by jciasenza** [comment]
I have tried different images and I see that the height problem is already solved.

**Comment by ihor-romaniuk** [comment]
@jciasenza This issue still reproduces on Safari browser.
<img width="1726" alt="image" src="https://github.com/user-attachments/assets/e8f5ab97-1b64-4c6b-b5cb-9ea7ce80f3d8">

**Comment by MaxFrank13** [comment]
I don't believe addressing this in Paragon would fix the issue because this instance of the `Card` component uses a custom `CourseCardImage` and not the `Card.ImageCap` provided by Paragon.

There is a PR up to address a fix specific to Learner Dashboard: #461
